// User & Role Types
export type Role = 'admin' | 'candidate';

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
}

// CV Status Types
export type CvStatus = 'uploaded' | 'parsing' | 'matrix_ready' | 'failed' | 'needs_review';

export interface CvFile {
  id: string;
  candidateId: string;
  filename: string;
  uploadedAt: Date;
  status: CvStatus;
  batchTag?: string;
  fileSize: number;
}

// Candidate Types
export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone: string;
  country: string;
  countryCode: string;
  headline?: string;
  cvFile?: CvFile;
  matrix?: CandidateMatrix;
  createdAt: Date;
  tags: string[];
}

// Matrix Types (generated by Qwen)
export interface SkillEntry {
  name: string;
  level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  yearsOfExperience: number;
}

export interface Evidence {
  id: string;
  text: string;
  category: string;
  source: string;
}

export interface CandidateMatrix {
  id: string;
  candidateId: string;
  skills: SkillEntry[];
  roles: string[];
  totalYearsExperience: number;
  domains: string[];
  education: {
    degree: string;
    institution: string;
    year: number;
  }[];
  languages: { language: string; proficiency: string }[];
  locationSignals: {
    currentCountry: string;
    willingToRelocate: boolean;
    preferredLocations: string[];
  };
  confidence: number;
  evidence: Evidence[];
  generatedAt: Date;
}

// Job Types
export type JobStatus = 'draft' | 'published' | 'closed';
export type LocationType = 'onsite' | 'hybrid' | 'remote';
export type SeniorityLevel = 'junior' | 'mid' | 'senior' | 'lead' | 'principal';

export interface Job {
  id: string;
  title: string;
  department: string;
  locationType: LocationType;
  country: string;
  city: string;
  description: string;
  mustHaveSkills: string[];
  niceToHaveSkills: string[];
  minYearsExperience: number;
  seniorityLevel: SeniorityLevel;
  status: JobStatus;
  createdAt: Date;
  matrix?: JobMatrix;
}

export interface JobMatrix {
  id: string;
  jobId: string;
  requiredSkills: { skill: string; weight: number }[];
  preferredSkills: { skill: string; weight: number }[];
  experienceWeight: number;
  locationWeight: number;
  domainWeight: number;
  generatedAt: Date;
}

// Match Types
export interface MatchBreakdown {
  skills: number;
  experience: number;
  domain: number;
  location: number;
}

export interface MatchGap {
  type: 'skill' | 'experience' | 'domain' | 'location';
  description: string;
  severity: 'minor' | 'moderate' | 'major';
}

export interface MatchResult {
  id: string;
  candidateId: string;
  jobId: string;
  score: number;
  breakdown: MatchBreakdown;
  explanation: string;
  gaps: MatchGap[];
  status: 'pending' | 'shortlisted' | 'rejected';
  calculatedAt: Date;
}

// Admin Notes & Tags
export interface AdminNote {
  id: string;
  candidateId: string;
  authorId: string;
  authorName: string;
  content: string;
  createdAt: Date;
}

export interface Tag {
  id: string;
  name: string;
  color: string;
}

// Dashboard Stats
export interface DashboardStats {
  totalCvs: number;
  processedCvs: number;
  needsReviewCvs: number;
  totalJobs: number;
  matchesGenerated: number;
}

// Upload Types
export interface UploadProgress {
  filename: string;
  progress: number;
  status: 'pending' | 'uploading' | 'success' | 'failed' | 'duplicate';
  error?: string;
}

export interface UploadResult {
  successful: number;
  failed: number;
  duplicates: number;
  files: UploadProgress[];
}
