// User & Role Types
export type Role = 'admin' | 'candidate' | 'company';

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  candidateId?: string;
  companyId?: string;
  companyName?: string;
  photoUrl?: string;
  logoUrl?: string;
}

// CV Status Types
export type CvStatus = 'uploaded' | 'parsing' | 'matrix_ready' | 'failed' | 'needs_review';

export interface CvFile {
  id: string;
  candidateId: string;
  filename: string;
  uploadedAt: Date;
  status: CvStatus;
  batchTag?: string;
  fileSize: number;
}

// Candidate Types
export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone: string;
  country: string;
  countryCode: string;
  headline?: string;
  cvFile?: CvFile;
  matrix?: CandidateMatrix;
  createdAt: Date;
  tags: string[];
}

export interface CandidateProfile {
  id: string;
  userId?: string;
  name: string;
  email: string;
  phone: string;
  country: string;
  countryCode: string;
  headline?: string;
  photoUrl?: string;
  bio?: string;
  linkedinUrl?: string;
  githubUrl?: string;
  portfolioUrl?: string;
  createdAt: Date;
  cvFile?: {
    id: string;
    filename: string;
    status: CvStatus;
    uploadedAt: Date;
  } | null;
  matrix?: CandidateMatrix | null;
}

// Company Types
export type CompanySize = '1-10' | '11-50' | '51-200' | '201-500' | '500+';

export interface CompanyProfile {
  id: string;
  userId: string;
  companyName: string;
  logoUrl?: string;
  industry?: string;
  companySize?: CompanySize;
  website?: string;
  description?: string;
  country?: string;
  city?: string;
  createdAt: Date;
}

// Matrix Types (generated by Qwen)
export interface SkillEntry {
  name: string;
  level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  yearsOfExperience: number;
}

export interface Evidence {
  id: string;
  text: string;
  category: string;
  source: string;
}

export interface CandidateMatrix {
  id: string;
  candidateId: string;
  skills: SkillEntry[];
  roles: string[];
  totalYearsExperience: number;
  domains: string[];
  education: {
    degree: string;
    institution: string;
    year: number;
  }[];
  languages: { language: string; proficiency: string }[];
  locationSignals: {
    currentCountry: string;
    willingToRelocate: boolean;
    preferredLocations: string[];
  };
  confidence: number;
  evidence: Evidence[];
  generatedAt: Date;
}

// Job Types
export type JobStatus = 'draft' | 'published' | 'closed';
export type LocationType = 'onsite' | 'hybrid' | 'remote';
export type SeniorityLevel = 'internship' | 'junior' | 'mid' | 'senior' | 'lead' | 'principal';

export interface Job {
  id: string;
  title: string;
  department: string;
  company?: string;
  companyId?: string;
  locationType: LocationType;
  country: string;
  city: string;
  description: string;
  mustHaveSkills: string[];
  niceToHaveSkills: string[];
  minYearsExperience: number;
  seniorityLevel: SeniorityLevel;
  status: JobStatus;
  deadline?: string | null;
  isFeatured?: boolean;
  createdAt: Date;
  matrix?: JobMatrix;
  // Browse extras
  companyProfile?: {
    id: string;
    companyName: string;
    logoUrl?: string;
    industry?: string;
    companySize?: string;
    website?: string;
    description?: string;
  } | null;
  matchScore?: number | null;
  applicationStatus?: ApplicationStatus | null;
  // Company view extras
  applicationCount?: number;
  hasMatrix?: boolean;
  totalApplications?: number;
  statusCounts?: Record<string, number>;
}

export interface JobMatrix {
  id: string;
  jobId: string;
  requiredSkills: { skill: string; weight: number }[];
  preferredSkills: { skill: string; weight: number }[];
  experienceWeight: number;
  locationWeight: number;
  domainWeight: number;
  generatedAt: Date;
}

// Match Types
export interface MatchBreakdown {
  skills: number;
  experience: number;
  domain: number;
  location: number;
}

export interface MatchGap {
  type: 'skill' | 'experience' | 'domain' | 'location';
  description: string;
  severity: 'minor' | 'moderate' | 'major';
}

export interface MatchResult {
  id: string;
  candidateId: string;
  jobId: string;
  score: number;
  breakdown: MatchBreakdown;
  explanation: string;
  gaps: MatchGap[];
  status: 'pending' | 'shortlisted' | 'rejected';
  calculatedAt: Date;
}

// Application Types
export type ApplicationStatus =
  | 'applied'
  | 'screening'
  | 'interview'
  | 'offer'
  | 'hired'
  | 'rejected'
  | 'withdrawn';

export interface Application {
  id: string;
  candidateId: string;
  jobId: string;
  status: ApplicationStatus;
  coverLetter?: string;
  appliedAt: string;
  updatedAt: string;
  matchScore?: number | null;
  matchBreakdown?: MatchBreakdown | null;
  matchExplanation?: string | null;
  matchGaps?: MatchGap[] | null;
  job?: {
    id: string;
    title: string;
    department: string;
    company?: string;
    locationType: LocationType;
    country: string;
    city: string;
    seniorityLevel: SeniorityLevel;
    status: JobStatus;
    createdAt: string;
    companyProfile?: {
      id: string;
      companyName: string;
      logoUrl?: string;
    } | null;
  } | null;
  candidate?: {
    id: string;
    name: string;
    email: string;
    phone?: string;
    country?: string;
    headline?: string;
    photoUrl?: string;
  } | null;
}

export interface BrowseJobsResponse {
  jobs: Job[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

export interface CompanyStats {
  activeJobs: number;
  totalApplications: number;
  shortlisted: number;
  hired: number;
  recentApplications: {
    id: string;
    status: ApplicationStatus;
    appliedAt: string;
    matchScore: number | null;
    candidate: {
      id: string;
      name: string;
      headline?: string;
      photoUrl?: string;
    } | null;
    job: {
      id: string;
      title: string;
    } | null;
  }[];
}

// Pipeline Stage Types
export interface PipelineStage {
  id: string;
  companyId: string;
  name: string;
  order: number;
  color: string;
  isDefault: boolean;
}

export interface PipelineApplication {
  id: string;
  candidateId: string;
  jobId: string;
  status: ApplicationStatus;
  appliedAt: string;
  updatedAt: string;
  matchScore: number | null;
  candidate: {
    id: string;
    name: string;
    email: string;
    phone?: string;
    headline?: string;
    photoUrl?: string;
    country?: string;
  } | null;
}

export interface PipelineColumn {
  id: string;
  name: string;
  order: number;
  color: string;
  isDefault: boolean;
  count: number;
  applications: PipelineApplication[];
}

export interface JobPipeline {
  job: {
    id: string;
    title: string;
    department: string;
    status: JobStatus;
  };
  stages: PipelineColumn[];
  totalApplications: number;
}

// Notification Types
export type NotificationType =
  | 'application_received'
  | 'status_changed'
  | 'shortlisted'
  | 'rejected'
  | 'new_match'
  | 'message_received'
  | 'job_expired';

export interface AppNotification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  data?: Record<string, any>;
  read: boolean;
  createdAt: string;
}

export interface NotificationListResponse {
  notifications: AppNotification[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Application History Types
export interface ApplicationHistoryEntry {
  id: string;
  applicationId: string;
  fromStatus: string;
  toStatus: string;
  changedBy: {
    id: string;
    name: string;
    role: string;
  } | null;
  note?: string;
  createdAt: string;
}

// Conversation & Messaging Types
export interface ConversationParticipant {
  id: string;
  name: string;
  photoUrl?: string | null;
  headline?: string | null;
  role: string;
}

export interface ConversationPreview {
  id: string;
  otherUser: ConversationParticipant;
  job?: { id: string; title: string } | null;
  lastMessage?: {
    id: string;
    content: string;
    senderId: string;
    createdAt: string;
    read: boolean;
  } | null;
  unreadCount: number;
  lastMessageAt: string | null;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  conversationId: string;
  senderId: string;
  senderName: string;
  senderRole: string;
  content: string;
  read: boolean;
  createdAt: string;
}

export interface MessagesResponse {
  messages: ChatMessage[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Saved Job Types
export interface SavedJobEntry {
  id: string;
  savedAt: string;
  job: (Job & { matchScore?: number | null }) | null;
}

// Analytics Types
export interface CompanyAnalytics {
  overview: {
    activeJobs: number;
    totalApplications: number;
    avgTimeToHire: number;
    conversionRate: number;
    hired: number;
  };
  applicationsOverTime: { date: string; count: number }[];
  pipelineConversion: Record<string, number>;
  topJobs: {
    id: string;
    title: string;
    status: string;
    applicationCount: number;
    avgMatchScore: number;
  }[];
  candidateLocations: Record<string, number>;
  skillsDemand: { skill: string; count: number }[];
}

export interface CandidateAnalytics {
  overview: {
    totalApplications: number;
    responseRate: number;
    avgMatchScore: number;
    interviewRate: number;
  };
  applicationsByStatus: Record<string, number>;
  matchScoreTrend: { jobTitle: string; score: number; appliedAt: string }[];
  skillsInDemand: { skill: string; count: number }[];
}

export interface AdminAnalytics {
  overview: {
    totalUsers: number;
    totalCandidates: number;
    totalCompanies: number;
    totalJobs: number;
    activeJobs: number;
    totalApplications: number;
    totalMatches: number;
  };
  userGrowth: { date: string; count: number }[];
  applicationGrowth: { date: string; count: number }[];
  topSkills: { skill: string; count: number }[];
  activeCompanies: { companyName: string; jobCount: number }[];
  statusDistribution: Record<string, number>;
}

// Team Member Types
export type MemberRole = 'owner' | 'admin' | 'recruiter' | 'viewer';
export type MemberStatus = 'pending' | 'active' | 'deactivated';

export interface TeamMember {
  id: string;
  email: string;
  role: MemberRole;
  status: MemberStatus;
  userName: string | null;
  userId: string | null;
  invitedAt: string;
  joinedAt: string | null;
}

// Privacy Types
export type ProfileVisibility = 'public' | 'applied_only' | 'hidden';

export interface PrivacySettings {
  profileVisibility: ProfileVisibility;
  showEmail: boolean;
  showPhone: boolean;
}

// ============================================================
//  AI Feature Types (Phase 6)
// ============================================================

export interface CvReviewResult {
  score: number;
  sections: { section: string; issues: string[]; suggestions: string[] }[];
  rewrittenBullets: { original: string; improved: string }[];
  summary: string;
}

export interface CvTailorResult {
  tailoredSections: { section: string; changes: string[] }[];
  keyChanges: string[];
  matchImprovement: { before: number; after: number };
}

export interface CoverLetterResult {
  coverLetter: string;
  alternateVersions: string[];
}

export interface JobPostingReviewResult {
  score: number;
  issues: { issue: string; severity: 'high' | 'medium' | 'low'; fix: string }[];
  suggestions: string[];
  rewrittenDescription: string;
  improvedTitle: string;
  inclusivityReport: string;
}

export interface GeneratedJobDescription {
  description: string;
  mustHaveSkills: string[];
  niceToHaveSkills: string[];
  suggestedSeniority: string;
  suggestedMinYears: number;
}

export interface InterviewQuestion {
  question: string;
  type: string;
  difficulty: string;
  expectedAnswer: string;
  scoringCriteria: string;
  relatedSkill: string;
}

export interface InterviewQuestionsResult {
  questions: InterviewQuestion[];
}

export interface CandidateSummaryResult {
  summary: string;
  strengths: string[];
  concerns: string[];
  fitReasoning: string;
}

export interface SkillGap {
  skill: string;
  importance: 'critical' | 'high' | 'medium' | 'low';
  currentLevel: string;
  requiredLevel: string;
  learningTime: string;
  impactOnScore: number;
}

export interface SkillGapAnalysisResult {
  gaps: SkillGap[];
  recommendations: string[];
  summary: string;
}

export interface SalaryEstimateResult {
  min: number;
  median: number;
  max: number;
  currency: string;
  factors: { factor: string; impact: string }[];
  marketComparison: string;
}

export interface AiChatResponse {
  response: string;
  suggestedActions?: string[];
}

export type CoverLetterTone = 'formal' | 'conversational' | 'enthusiastic';

// Admin Notes & Tags
export interface AdminNote {
  id: string;
  candidateId: string;
  authorId: string;
  authorName: string;
  content: string;
  createdAt: Date;
}

export interface Tag {
  id: string;
  name: string;
  color: string;
}

// Dashboard Stats
export interface DashboardStats {
  totalCvs: number;
  processedCvs: number;
  needsReviewCvs: number;
  totalJobs: number;
  matchesGenerated: number;
}

// Upload Types
export interface UploadProgress {
  filename: string;
  progress: number;
  status: 'pending' | 'uploading' | 'success' | 'failed' | 'duplicate';
  error?: string;
}

export interface UploadResult {
  successful: number;
  failed: number;
  duplicates: number;
  files: UploadProgress[];
}

// Job Report Types
export interface ReportStatistics {
  totalMatches: number;
  averageScore: number;
  scoreDistribution: {
    '90-100': number;
    '80-89': number;
    '70-79': number;
    '60-69': number;
    '45-59': number;
  };
  topSkills: Array<{ skill: string; count: number }>;
  experienceDistribution: {
    '0-2': number;
    '3-5': number;
    '6-10': number;
    '11+': number;
  };
  locationDistribution: Record<string, number>;
  domainDistribution: Record<string, number>;
}

export interface JobReport {
  id: string;
  jobId: string;
  reportData: {
    job: Job;
    statistics: ReportStatistics;
    topCandidates: Array<{
      id: string;
      name: string;
      email: string;
      phone: string;
      country: string;
      headline?: string;
      matchScore: number;
      matchBreakdown: MatchBreakdown;
      matchExplanation: string;
      matchGaps: MatchGap[];
      experience: number;
      skills: SkillEntry[];
      domains: string[];
    }>;
    recommendations: string[];
  };
  status: 'generating' | 'completed' | 'failed';
  generatedAt: Date;
  generatedBy?: string;
}
