import { useState } from 'react';
import type { CandidateMatrix, JobMatrix } from '@/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import { Sparkles, GraduationCap, Globe, MapPin, Briefcase, Pencil, Save, X, RotateCcw, Plus, Trash2, ArrowRightLeft } from 'lucide-react';

interface CandidateMatrixViewProps {
  matrix: CandidateMatrix;
}

interface JobMatrixViewProps {
  matrix: JobMatrix;
  onSave?: (matrix: {
    requiredSkills: { skill: string; weight: number }[];
    preferredSkills: { skill: string; weight: number }[];
    experienceWeight: number;
    locationWeight: number;
    domainWeight: number;
  }) => Promise<void>;
  saving?: boolean;
}

const skillLevelColors: Record<string, string> = {
  beginner: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
  intermediate: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300',
  advanced: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
  expert: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300',
};

export function CandidateMatrixView({ matrix }: CandidateMatrixViewProps) {
  return (
    <div className="space-y-4" data-testid="candidate-matrix-view">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Sparkles className="w-4 h-4" />
        <span>Matrix generated by Qwen (latest)</span>
        <Badge variant="secondary" className="text-xs">
          {matrix.confidence}% confidence
        </Badge>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Briefcase className="w-4 h-4" />
              Skills
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {matrix.skills.map((skill) => (
                <Badge
                  key={skill.name}
                  variant="outline"
                  className={skillLevelColors[skill.level]}
                >
                  {skill.name}
                  <span className="ml-1 text-[10px] opacity-70">
                    {skill.yearsOfExperience}y
                  </span>
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <GraduationCap className="w-4 h-4" />
              Education
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {matrix.education.map((edu, i) => (
                <div key={i} className="text-sm">
                  <p className="font-medium">{edu.degree}</p>
                  <p className="text-muted-foreground">
                    {edu.institution} ({edu.year})
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Globe className="w-4 h-4" />
              Languages
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {matrix.languages.map((lang) => (
                <Badge key={lang.language} variant="secondary">
                  {lang.language}
                  <span className="ml-1 text-[10px] opacity-70">
                    ({lang.proficiency})
                  </span>
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <MapPin className="w-4 h-4" />
              Location Signals
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <p className="text-sm">
              <span className="text-muted-foreground">Current:</span>{' '}
              {matrix.locationSignals.currentCountry}
            </p>
            <p className="text-sm">
              <span className="text-muted-foreground">Relocate:</span>{' '}
              {matrix.locationSignals.willingToRelocate ? 'Yes' : 'No'}
            </p>
            {matrix.locationSignals.preferredLocations.length > 0 && (
              <div className="flex flex-wrap gap-1">
                {matrix.locationSignals.preferredLocations.map((loc) => (
                  <Badge key={loc} variant="outline" className="text-xs">
                    {loc}
                  </Badge>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-medium">Experience Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <p className="text-2xl font-bold">{matrix.totalYearsExperience}</p>
              <p className="text-xs text-muted-foreground">Years Experience</p>
            </div>
            <div>
              <p className="text-2xl font-bold">{matrix.skills.length}</p>
              <p className="text-xs text-muted-foreground">Skills Identified</p>
            </div>
            <div>
              <p className="text-2xl font-bold">{matrix.domains.length}</p>
              <p className="text-xs text-muted-foreground">Domains</p>
            </div>
            <div>
              <p className="text-2xl font-bold">{matrix.roles.length}</p>
              <p className="text-xs text-muted-foreground">Roles</p>
            </div>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            {matrix.domains.map((domain) => (
              <Badge key={domain} variant="outline">
                {domain}
              </Badge>
            ))}
            {matrix.roles.map((role) => (
              <Badge key={role} variant="secondary">
                {role}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// Editable skill row
function EditableSkillRow({
  skill,
  weight,
  color,
  onSkillChange,
  onWeightChange,
  onRemove,
  onMove,
  moveLabel,
}: {
  skill: string;
  weight: number;
  color: string;
  onSkillChange: (name: string) => void;
  onWeightChange: (weight: number) => void;
  onRemove: () => void;
  onMove: () => void;
  moveLabel: string;
}) {
  return (
    <div className="flex items-center gap-2 group">
      <Input
        value={skill}
        onChange={(e) => onSkillChange(e.target.value)}
        className="h-7 text-sm flex-1 min-w-0"
      />
      <div className="flex items-center gap-1.5 shrink-0">
        <div className="w-16">
          <Slider
            value={[weight]}
            onValueChange={([v]) => onWeightChange(v)}
            max={100}
            min={0}
            step={5}
            className="w-full"
          />
        </div>
        <span className="text-xs text-muted-foreground w-8 text-right">{weight}%</span>
      </div>
      <button
        onClick={onMove}
        className="opacity-0 group-hover:opacity-100 transition-opacity p-1 rounded hover:bg-muted"
        title={moveLabel}
      >
        <ArrowRightLeft className="w-3 h-3 text-muted-foreground" />
      </button>
      <button
        onClick={onRemove}
        className="opacity-0 group-hover:opacity-100 transition-opacity p-1 rounded hover:bg-destructive/10"
        title="Remove skill"
      >
        <Trash2 className="w-3 h-3 text-destructive" />
      </button>
    </div>
  );
}

// Read-only skill row
function SkillRow({ skill, weight, color }: { skill: string; weight: number; color: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-sm">{skill}</span>
      <div className="flex items-center gap-2">
        <div className="w-20 h-1.5 rounded-full bg-muted overflow-hidden">
          <div className={`h-full rounded-full ${color}`} style={{ width: `${weight}%` }} />
        </div>
        <span className="text-xs text-muted-foreground w-8">{weight}%</span>
      </div>
    </div>
  );
}

export function JobMatrixView({ matrix, onSave, saving }: JobMatrixViewProps) {
  const [editing, setEditing] = useState(false);

  // Editable state
  const [requiredSkills, setRequiredSkills] = useState(matrix.requiredSkills.map(s => ({ ...s })));
  const [preferredSkills, setPreferredSkills] = useState(matrix.preferredSkills.map(s => ({ ...s })));
  const [experienceWeight, setExperienceWeight] = useState(matrix.experienceWeight);
  const [locationWeight, setLocationWeight] = useState(matrix.locationWeight);
  const [domainWeight, setDomainWeight] = useState(matrix.domainWeight);
  const [newRequiredSkill, setNewRequiredSkill] = useState('');
  const [newPreferredSkill, setNewPreferredSkill] = useState('');

  const skillsWeight = 100 - experienceWeight - locationWeight - domainWeight;

  const handleStartEdit = () => {
    // Reset to current matrix values
    setRequiredSkills(matrix.requiredSkills.map(s => ({ ...s })));
    setPreferredSkills(matrix.preferredSkills.map(s => ({ ...s })));
    setExperienceWeight(matrix.experienceWeight);
    setLocationWeight(matrix.locationWeight);
    setDomainWeight(matrix.domainWeight);
    setEditing(true);
  };

  const handleCancel = () => {
    setEditing(false);
    setNewRequiredSkill('');
    setNewPreferredSkill('');
  };

  const handleReset = () => {
    setRequiredSkills(matrix.requiredSkills.map(s => ({ ...s })));
    setPreferredSkills(matrix.preferredSkills.map(s => ({ ...s })));
    setExperienceWeight(matrix.experienceWeight);
    setLocationWeight(matrix.locationWeight);
    setDomainWeight(matrix.domainWeight);
  };

  const handleSave = async () => {
    if (!onSave) return;
    await onSave({
      requiredSkills: requiredSkills.filter(s => s.skill.trim()),
      preferredSkills: preferredSkills.filter(s => s.skill.trim()),
      experienceWeight,
      locationWeight,
      domainWeight,
    });
    setEditing(false);
  };

  const addRequiredSkill = () => {
    if (!newRequiredSkill.trim()) return;
    setRequiredSkills([...requiredSkills, { skill: newRequiredSkill.trim(), weight: 70 }]);
    setNewRequiredSkill('');
  };

  const addPreferredSkill = () => {
    if (!newPreferredSkill.trim()) return;
    setPreferredSkills([...preferredSkills, { skill: newPreferredSkill.trim(), weight: 50 }]);
    setNewPreferredSkill('');
  };

  const moveToPreferred = (index: number) => {
    const skill = requiredSkills[index];
    setRequiredSkills(requiredSkills.filter((_, i) => i !== index));
    setPreferredSkills([...preferredSkills, { ...skill, weight: Math.min(skill.weight, 60) }]);
  };

  const moveToRequired = (index: number) => {
    const skill = preferredSkills[index];
    setPreferredSkills(preferredSkills.filter((_, i) => i !== index));
    setRequiredSkills([...requiredSkills, { ...skill, weight: Math.max(skill.weight, 70) }]);
  };

  // ===== EDIT MODE =====
  if (editing) {
    return (
      <div className="space-y-4" data-testid="job-matrix-view">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Pencil className="w-4 h-4" />
            <span>Editing Job Matrix</span>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={handleReset} className="gap-1.5 text-xs">
              <RotateCcw className="w-3 h-3" />
              Reset to AI
            </Button>
            <Button variant="ghost" size="sm" onClick={handleCancel} className="gap-1.5 text-xs">
              <X className="w-3 h-3" />
              Cancel
            </Button>
            <Button size="sm" onClick={handleSave} disabled={saving} className="gap-1.5 text-xs">
              <Save className="w-3 h-3" />
              {saving ? 'Saving...' : 'Save Changes'}
            </Button>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          {/* Required Skills */}
          <Card className="border-primary/30">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium">Required Skills</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {requiredSkills.map((s, i) => (
                  <EditableSkillRow
                    key={`req-${i}`}
                    skill={s.skill}
                    weight={s.weight}
                    color="bg-primary"
                    onSkillChange={(name) => {
                      const updated = [...requiredSkills];
                      updated[i] = { ...updated[i], skill: name };
                      setRequiredSkills(updated);
                    }}
                    onWeightChange={(w) => {
                      const updated = [...requiredSkills];
                      updated[i] = { ...updated[i], weight: w };
                      setRequiredSkills(updated);
                    }}
                    onRemove={() => setRequiredSkills(requiredSkills.filter((_, idx) => idx !== i))}
                    onMove={() => moveToPreferred(i)}
                    moveLabel="Move to Preferred"
                  />
                ))}
                <div className="flex items-center gap-2 pt-2 border-t">
                  <Input
                    value={newRequiredSkill}
                    onChange={(e) => setNewRequiredSkill(e.target.value)}
                    placeholder="Add skill..."
                    className="h-7 text-sm flex-1"
                    onKeyDown={(e) => e.key === 'Enter' && addRequiredSkill()}
                  />
                  <Button variant="ghost" size="sm" onClick={addRequiredSkill} className="h-7 px-2">
                    <Plus className="w-3 h-3" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Preferred Skills */}
          <Card className="border-emerald-500/30">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium">Preferred Skills</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {preferredSkills.map((s, i) => (
                  <EditableSkillRow
                    key={`pref-${i}`}
                    skill={s.skill}
                    weight={s.weight}
                    color="bg-emerald-500"
                    onSkillChange={(name) => {
                      const updated = [...preferredSkills];
                      updated[i] = { ...updated[i], skill: name };
                      setPreferredSkills(updated);
                    }}
                    onWeightChange={(w) => {
                      const updated = [...preferredSkills];
                      updated[i] = { ...updated[i], weight: w };
                      setPreferredSkills(updated);
                    }}
                    onRemove={() => setPreferredSkills(preferredSkills.filter((_, idx) => idx !== i))}
                    onMove={() => moveToRequired(i)}
                    moveLabel="Move to Required"
                  />
                ))}
                <div className="flex items-center gap-2 pt-2 border-t">
                  <Input
                    value={newPreferredSkill}
                    onChange={(e) => setNewPreferredSkill(e.target.value)}
                    placeholder="Add skill..."
                    className="h-7 text-sm flex-1"
                    onKeyDown={(e) => e.key === 'Enter' && addPreferredSkill()}
                  />
                  <Button variant="ghost" size="sm" onClick={addPreferredSkill} className="h-7 px-2">
                    <Plus className="w-3 h-3" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Matching Weights */}
        <Card className="border-amber-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Matching Weights</CardTitle>
            <p className="text-xs text-muted-foreground">Must total 100%. Skills weight adjusts automatically.</p>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div className="space-y-2">
                <div className="text-center">
                  <p className={`text-2xl font-bold ${skillsWeight < 0 ? 'text-destructive' : 'text-blue-600 dark:text-blue-400'}`}>
                    {skillsWeight}%
                  </p>
                  <p className="text-xs text-muted-foreground">Skills (auto)</p>
                </div>
              </div>
              <div className="space-y-2">
                <div className="text-center">
                  <p className="text-2xl font-bold text-primary">{experienceWeight}%</p>
                  <p className="text-xs text-muted-foreground mb-2">Experience</p>
                  <Slider
                    value={[experienceWeight]}
                    onValueChange={([v]) => setExperienceWeight(v)}
                    max={60}
                    min={0}
                    step={5}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <div className="text-center">
                  <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">{locationWeight}%</p>
                  <p className="text-xs text-muted-foreground mb-2">Location</p>
                  <Slider
                    value={[locationWeight]}
                    onValueChange={([v]) => setLocationWeight(v)}
                    max={40}
                    min={0}
                    step={5}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <div className="text-center">
                  <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{domainWeight}%</p>
                  <p className="text-xs text-muted-foreground mb-2">Domain</p>
                  <Slider
                    value={[domainWeight]}
                    onValueChange={([v]) => setDomainWeight(v)}
                    max={40}
                    min={0}
                    step={5}
                  />
                </div>
              </div>
            </div>
            {skillsWeight < 0 && (
              <p className="text-xs text-destructive mt-2 text-center">
                Weights exceed 100%! Reduce Experience, Location, or Domain weights.
              </p>
            )}
          </CardContent>
        </Card>
      </div>
    );
  }

  // ===== VIEW MODE =====
  return (
    <div className="space-y-4" data-testid="job-matrix-view">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Sparkles className="w-4 h-4" />
          <span>Matrix generated by Qwen (latest)</span>
        </div>
        {onSave && (
          <Button variant="outline" size="sm" onClick={handleStartEdit} className="gap-1.5 text-xs">
            <Pencil className="w-3 h-3" />
            Edit Matrix
          </Button>
        )}
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Required Skills</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {matrix.requiredSkills.map(({ skill, weight }) => (
                <SkillRow key={skill} skill={skill} weight={weight} color="bg-primary" />
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Preferred Skills</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {matrix.preferredSkills.map(({ skill, weight }) => (
                <SkillRow key={skill} skill={skill} weight={weight} color="bg-emerald-500" />
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-medium">Matching Weights</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-4 gap-4">
            <div className="text-center">
              <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">{skillsWeight}%</p>
              <p className="text-xs text-muted-foreground">Skills</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-primary">{matrix.experienceWeight}%</p>
              <p className="text-xs text-muted-foreground">Experience</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">
                {matrix.locationWeight}%
              </p>
              <p className="text-xs text-muted-foreground">Location</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                {matrix.domainWeight}%
              </p>
              <p className="text-xs text-muted-foreground">Domain</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
