import type { CandidateMatrix, JobMatrix } from '@/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Sparkles, GraduationCap, Globe, MapPin, Briefcase } from 'lucide-react';

interface CandidateMatrixViewProps {
  matrix: CandidateMatrix;
}

interface JobMatrixViewProps {
  matrix: JobMatrix;
}

const skillLevelColors: Record<string, string> = {
  beginner: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
  intermediate: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300',
  advanced: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
  expert: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300',
};

export function CandidateMatrixView({ matrix }: CandidateMatrixViewProps) {
  return (
    <div className="space-y-4" data-testid="candidate-matrix-view">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Sparkles className="w-4 h-4" />
        <span>Matrix generated by Qwen (latest)</span>
        <Badge variant="secondary" className="text-xs">
          {matrix.confidence}% confidence
        </Badge>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Briefcase className="w-4 h-4" />
              Skills
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {matrix.skills.map((skill) => (
                <Badge
                  key={skill.name}
                  variant="outline"
                  className={skillLevelColors[skill.level]}
                >
                  {skill.name}
                  <span className="ml-1 text-[10px] opacity-70">
                    {skill.yearsOfExperience}y
                  </span>
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <GraduationCap className="w-4 h-4" />
              Education
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {matrix.education.map((edu, i) => (
                <div key={i} className="text-sm">
                  <p className="font-medium">{edu.degree}</p>
                  <p className="text-muted-foreground">
                    {edu.institution} ({edu.year})
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Globe className="w-4 h-4" />
              Languages
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {matrix.languages.map((lang) => (
                <Badge key={lang.language} variant="secondary">
                  {lang.language}
                  <span className="ml-1 text-[10px] opacity-70">
                    ({lang.proficiency})
                  </span>
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <MapPin className="w-4 h-4" />
              Location Signals
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <p className="text-sm">
              <span className="text-muted-foreground">Current:</span>{' '}
              {matrix.locationSignals.currentCountry}
            </p>
            <p className="text-sm">
              <span className="text-muted-foreground">Relocate:</span>{' '}
              {matrix.locationSignals.willingToRelocate ? 'Yes' : 'No'}
            </p>
            {matrix.locationSignals.preferredLocations.length > 0 && (
              <div className="flex flex-wrap gap-1">
                {matrix.locationSignals.preferredLocations.map((loc) => (
                  <Badge key={loc} variant="outline" className="text-xs">
                    {loc}
                  </Badge>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-medium">Experience Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <p className="text-2xl font-bold">{matrix.totalYearsExperience}</p>
              <p className="text-xs text-muted-foreground">Years Experience</p>
            </div>
            <div>
              <p className="text-2xl font-bold">{matrix.skills.length}</p>
              <p className="text-xs text-muted-foreground">Skills Identified</p>
            </div>
            <div>
              <p className="text-2xl font-bold">{matrix.domains.length}</p>
              <p className="text-xs text-muted-foreground">Domains</p>
            </div>
            <div>
              <p className="text-2xl font-bold">{matrix.roles.length}</p>
              <p className="text-xs text-muted-foreground">Roles</p>
            </div>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            {matrix.domains.map((domain) => (
              <Badge key={domain} variant="outline">
                {domain}
              </Badge>
            ))}
            {matrix.roles.map((role) => (
              <Badge key={role} variant="secondary">
                {role}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

export function JobMatrixView({ matrix }: JobMatrixViewProps) {
  return (
    <div className="space-y-4" data-testid="job-matrix-view">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Sparkles className="w-4 h-4" />
        <span>Matrix generated by Qwen (latest)</span>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Required Skills</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {matrix.requiredSkills.map(({ skill, weight }) => (
                <div key={skill} className="flex items-center justify-between">
                  <span className="text-sm">{skill}</span>
                  <div className="flex items-center gap-2">
                    <div className="w-20 h-1.5 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full rounded-full bg-primary"
                        style={{ width: `${weight}%` }}
                      />
                    </div>
                    <span className="text-xs text-muted-foreground w-8">{weight}%</span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Preferred Skills</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {matrix.preferredSkills.map(({ skill, weight }) => (
                <div key={skill} className="flex items-center justify-between">
                  <span className="text-sm">{skill}</span>
                  <div className="flex items-center gap-2">
                    <div className="w-20 h-1.5 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full rounded-full bg-emerald-500"
                        style={{ width: `${weight}%` }}
                      />
                    </div>
                    <span className="text-xs text-muted-foreground w-8">{weight}%</span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-medium">Matching Weights</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-4">
            <div className="text-center">
              <p className="text-2xl font-bold text-primary">{matrix.experienceWeight}%</p>
              <p className="text-xs text-muted-foreground">Experience</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">
                {matrix.locationWeight}%
              </p>
              <p className="text-xs text-muted-foreground">Location</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                {matrix.domainWeight}%
              </p>
              <p className="text-xs text-muted-foreground">Domain</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
